sudo: required

language: go

services:
  - docker

go:
  - master

install:
  - docker build -t $DOCKER_USERNAME/go-server-example .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/go-server-example;
    fi
